version: '3'
services:
  app:
    build: .
    entrypoint: "sh docker-entrypoint.sh"
    command: "mix phx.server"
    volumes:
      - .:/inmana
    ports:
      - "4000:4000"
    env_file: .env.docker
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:9.6.19
    environment:
      - POSTGRES_DB=inmana_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db-data-pg-inmana:/var/lib/postgresql

volumes:
  db-data-pg-inmana: